openapi: 3.0.0
info:
  version: 1.0.0
  title: Gorilla Farm Api
  description: |
    ゴリラを放牧している牧場のAPI

    ゴリラの飼育情報や飼育者の情報を取得したり更新する

tags:
  - name: Gorilla
    description: ゴリラに関連する情報を扱う
paths:
  /gorillas:
    get:
      tags:
        - Gorilla
      description: >
        飼育しているゴリラの一覧を取得する
      parameters:
        - name: page
          in: query
          description: |
            取得したいページの位置を設定する
          schema:
            type: number
            minimum: 1
          required: true

        - name: pageSize
          in: query
          description: |
            取得したいレコードの数を設定する 
          schema:
            type: number
            minimum: 1
          required: true
          
      responses:
        '200':
          description: 取得
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Gorilla'
components:
  schemas:
    Gorilla:
      type: "object"
      required:
        - "name"
        - "animal_type"
      properties:
        id:
          type: "integer"
          format: "int64"
          example: 100
        name:
          type: "string"
          description: "ゴリラの名前"
          example: "太郎"
        animal_type:
          type: "string"
          description: "ゴリラの種別"
          enum:
            - "WesternLowlandGorilla"
            - "CrossRiverGorilla"
            - "MountainGorilla"
            - "EasternLowlandGorilla"
    Error:
      type: "object"
      properties:
        code:
          type: "integer"
          format: "int32"
          enum:
            - 1
            - 2
            - 3
            - 4
            - 5
            - 6
            - 7
            - 8
            - 9
        type:
          type: "string"
          enum:
            - bad_request
            - unauthorized_token
            - forbidden
            - not_found
            - internal_server_error
            - too_many_requests
            - plan_limit_exceeded
            - non_deletable_resource
            - service_maintenance
        message:
          type: "string"
          description: エラーの原因
